### PR TITLE
Add deprecation notice

### PR DESCRIPTION
**Pull request by fregante**
Follows https://github.com/jdm-contrib/jdm/pull/1782

It might be a good idea to archive the repo after this PR, to signal its closure

### CODE REVIEW

**Comment by tupaschoal** [comment]
Don't you want to move your repo into the org? There are two options I can think of:
1 - You PR deleting everything from this repo and then replacing with what you created (and we can make you a maintainer)
2 - We archive this repo and get yours into the organization

I'd rather have 1 just for the sake of maintaining a history of the extensions on a single repo, but your call. I'd love for one of these to be picked, though, for us to start linking to the new extension version.

**Comment by fregante** [comment]
I don’t think either one is possible because the repo contains the Chrome Web Store token with access to all of my extensions, in order to automate publishing.

I know this might be suboptimal, but I did mention this requirement in that thread. I can maintain it if it's easy to. If not, the old extension would work just as well, if someone published it.

**Comment by fregante** [comment]
A third compromise could be the number 1, but also transferring this repo to my account so that:

- its history is preserved
- no organization user has access to my token

**Comment by tupaschoal** [comment]
Hi @fregante,

I gave this some thought and we did mention our desire to bring it up to our repo in the [original thread](https://github.com/jdm-contrib/jdm/issues/1772#issuecomment-1721278112). Can't we have a Chrome Web Store token just for this, so that the repo could be transferred into the org and not compromising your other extensions?

**Comment by fregante** [comment]
Unfortunately tokens are global, so to achieve that we'd have to:

- create a new Google account
- create a new Chrome Web Store user ($5)
- create the token from that account

The last step alone is quite [lengthy](https://github.com/fregante/chrome-webstore-upload/blob/HEAD/How%20to%20generate%20Google%20API%20keys.md) and I'm not sure I'd want to do all that.

**Comment by fregante** [comment]
This is why I need easy access to the extension to actually support it:

Screenshot 2


---

I pushed a new release, let's see if it's enough for them.

**Comment by tupaschoal** [comment]
Hi @fregante, sorry for taking a while to reach back.

I'm willing to setup the things on a dedicated account (including paying the one time $5 fee) for us to take the repo into the organization. If I understand correctly, that would only require, from you to:
1. Wipe out your secrets from the repo
2. Transfer the repo

Then I could populate it with the secrets on the new account and the publish, if you need to do extra modifications, would be done automatically from  the CI.

**Comment by fregante** [comment]
I understand, but if it's not going to stay in my name, you might as well fork it and publish it autonomously. I might have mentioned it before, but I'm not interested in maintaining software for others.

**Comment by tupaschoal** [comment]
You'd still retain maintainer rights over the repo and I don't mind if you add credits on your name there and on the extension itself. The only difference is that it would be under the jdm org and credentials to publish, so that it seems more "official", from a user standpoint. Does that not suffice?

**Comment by fregante** [comment]
> maintainer rights

That's "maintaining software for others" paraphrased. I already offered an alternative solution: fork and publish autonomously. I can pass the listing to your account if you want to preserve its 454 users.

**Comment by tupaschoal** [comment]
Since we could not agree on centralizing the maintenance, I've updated the top of this project README to contain links to your extension and am archiving the repository.

**Pull request closed without merging**
